name: Test Flask App

on:
  push:
    branches: ["main"]


jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - name: Install python 
        shell: bash
        run: python3 --version
      - name: Install requirements
        working-directory: flask-project
        shell: bash
        run: pip install -r requirements.txt
