name: Test Flask App

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - name: Install python 
        shell: bash
        run: python3 --version

      - name: Install requirements
        shell: bash
        run: pip install flask Flask-SQLAlchemy flask-login
        
      - name: Run Aplication
        working-directory: flask-project
        shell: bash 
        run: flask run
